readme & FirstController
eptrubnikova/CookBook pull request #1
Opened 2023-01-30 15:05 UTC by eptrubnikova

2023-02-06 19:08 UTC, alekseykoshelev requested changes

2023-02-06 19:08 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/model/Ingredient.java
> +    private static String nameIngredient;
static не нужен, иначе все у всех будет одинаковое.

2023-02-06 19:08 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/model/Ingredient.java
> +    private static int idCount = 0;
Тут нужно оставить, счетчик как раз должен быть static

2023-02-06 19:08 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/services/RecipeService.java
> +    Recipe getRecipe(Integer lastId);
А почему last? Ведь не обязательно последний)

2023-02-06 19:08 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/services/impl/IngredientServiceImpl.java
> +        if (ingredients.containsKey(lastId)) {
тут можно сразу возвращать ингредиент `ingredients.get(lastId);`, но нужно учесть, что может вернуться `null`.

2023-02-06 19:08 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/services/impl/RecipeServiceImpl.java
> +        if (recipes.containsKey(lastId)) {
if ничего не делает, нужно удалить

2023-02-06 19:08 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/controllers/IngredientController.java
> +        if (result == null) {
Тут проверка на null как раз есть, отлично!

2023-02-07 08:41 UTC, eptrubnikova commented on src/main/java/me/trubnikova/cookbook/model/Ingredient.java
> +    private static String nameIngredient;
удалила статик у всех полей, кроме счетчика

2023-02-07 08:42 UTC, eptrubnikova commented on src/main/java/me/trubnikova/cookbook/model/Ingredient.java
> +    private static int idCount = 0;
оставила статик у idCount

2023-02-07 08:42 UTC, eptrubnikova commented on src/main/java/me/trubnikova/cookbook/services/RecipeService.java
> +    Recipe getRecipe(Integer lastId);
откорректировала на id)

2023-02-07 08:44 UTC, eptrubnikova commented on src/main/java/me/trubnikova/cookbook/services/impl/IngredientServiceImpl.java
> +        if (ingredients.containsKey(lastId)) {
проверку на null сделала в контроллере

2023-02-07 08:44 UTC, eptrubnikova commented on src/main/java/me/trubnikova/cookbook/services/impl/RecipeServiceImpl.java
> +        if (recipes.containsKey(lastId)) {
добавила условие, что если id не найден, то выходит соответствующее сообщение

2023-02-07 19:24 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/services/impl/RecipeServiceImpl.java
> +    private static Integer id = 0;
А ведь у тебя в классе Recipe есть id. В ингредиентах как раз его используешь)

2023-02-07 19:24 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/services/IngredientService.java
> +    int addIngredient(Ingredient ingredient);
Может тут тоже вернуть Ingredient? Чтобы было также как в рецептах.

2023-02-08 16:57 UTC, eptrubnikova commented on src/main/java/me/trubnikova/cookbook/services/impl/RecipeServiceImpl.java
> +    private static Integer id = 0;
Алексей, честно, не поняла ошибку!

2023-02-08 16:58 UTC, eptrubnikova commented on src/main/java/me/trubnikova/cookbook/services/IngredientService.java
> +    int addIngredient(Ingredient ingredient);
Изменила метод.

2023-02-09 19:07 UTC, alekseykoshelev commented on src/main/java/me/trubnikova/cookbook/services/impl/RecipeServiceImpl.java
> +    private static Integer id = 0;
Тут имел ввиду, что можно брать id из объекта recipe. Например, в методе `addRecipe`. Можно вместо этого счетчика делать `recipe.getId()`

2023-02-12 11:49 UTC, isavinov approved these changes

2023-02-12 14:34 UTC, merged